# Generated by Django 4.2.3 on 2023-08-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followchatapp', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default-profile.jpg', null=True, upload_to='img'),
        ),
    ]
