# Generated by Django 4.2.3 on 2023-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followchatapp', '0011_alter_friend_profile_alter_profile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
